import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  sendPasswordResetEmail,
  onAuthStateChanged,
  signOut,
  deleteUser,
  EmailAuthProvider,
  reauthenticateWithCredential,
  fetchSignInMethodsForEmail,
  updatePassword,
  verifyPasswordResetCode,
  confirmPasswordReset,
  GoogleAuthProvider,
  signInWithPopup,
  reauthenticateWithPopup,
  linkWithPopup,
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import {
  getFirestore,
  setDoc,
  doc,
  getDoc,
  collection,
  getDocs,
  query,
  where,
  updateDoc,
  deleteDoc,
  serverTimestamp,
  addDoc,
  orderBy,
  limit,
  deleteField,
  onSnapshot,
  increment,
  or,
  startAfter,
  and,
  Timestamp,
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import {
  getDatabase,
  ref,
  push,
  set,
  get,
  update,
  remove,
  onValue,
  off,
  onChildAdded,
  onChildChanged,
  onChildRemoved,
  serverTimestamp as rtdbServerTimestamp,
  query as rtdbQuery,
  orderByChild,
  equalTo,
  limitToLast,
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";

const firebaseConfig = {
  apiKey: "AIzaSyDhV0RW9BRTIPxyGb6p1xgcnqeHV-yijKg",
  authDomain: "vivarq-argentina.firebaseapp.com",
  databaseURL: "https://vivarq-argentina-default-rtdb.firebaseio.com",
  projectId: "vivarq-argentina",
  storageBucket: "vivarq-argentina.firebasestorage.app",
  messagingSenderId: "317459457081",
  appId: "1:317459457081:web:b1df2d51ff34b3339299e8",
  measurementId: "G-E37WG2MBYY",
};

const app = initializeApp(firebaseConfig);
const auth = getAuth();
const db = getFirestore();
const rtdb = getDatabase();

export {
  // Auth
  getAuth,
  auth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  sendPasswordResetEmail,
  onAuthStateChanged,
  signOut,
  deleteUser,
  EmailAuthProvider,
  reauthenticateWithCredential,
  fetchSignInMethodsForEmail,
  updatePassword,
  verifyPasswordResetCode,
  confirmPasswordReset,
  GoogleAuthProvider,
  signInWithPopup,
  reauthenticateWithPopup,
  linkWithPopup,

  // Firestore
  db,
  getFirestore,
  setDoc,
  doc,
  getDoc,
  collection,
  getDocs,
  query,
  where,
  updateDoc,
  deleteDoc,
  serverTimestamp,
  addDoc,
  orderBy,
  limit,
  deleteField,
  onSnapshot,
  increment,
  or,
  and,
  startAfter,
  Timestamp,

  // Realtime Database
  rtdb,
  getDatabase,
  ref,
  push,
  set,
  get,
  update,
  remove,
  onValue,
  off,
  onChildAdded,
  onChildChanged,
  onChildRemoved,
  rtdbServerTimestamp,
  rtdbQuery,
  orderByChild,
  equalTo,
  limitToLast,
};
